[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "exif-analyzer"
version = "0.1.0"
description = "EXIF metadata analyzer and statistics tool"
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "Matteo Muscella" }
]

dependencies = [
  "pyexiftool"
]

[project.scripts]
exif-analyzer = "exif_analyzer.runner:main"
